language: node_js

branches:
  only:
  - master
  - /^release\/.*$/

node_js:
  - '10'

os:
  - linux

env:
  # This stops Windows builds from hanging
  # https://travis-ci.community/t/timeout-after-build-finished-and-succeeded/1336
  - YARN_GPG=no

addons:
  apt:
    packages:
      # Fixes error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
      # https://github.com/electron/electron/issues/1518
      - libgconf-2-4
      # Ensure chrome is the latest version
      # https://stackoverflow.com/questions/57903415/travis-ci-chrome-62-instead-of-77
      - dpkg
  chrome: stable

before_install:
  # prevents windows error: npm ERR! ... git-sh-setup: file not found
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export PATH=/c/PROGRA~1/Git/usr/bin:/c/PROGRA~1/Git/mingw64/libexec/git-core:$PATH ; fi

script: npx nyc -s npm run test:node -- -- -- --timeout 10000 --bail
after_success:
  - npx nyc report --reporter=text-lcov > coverage.lcov && npx codecov
after_failure:
  - echo ./
  - ls -la
  - echo ./packages/ipfs
  - ls -la ./packages/ipfs
  - echo /tmp
  - ls -l /tmp
  - cat /tmp/crash.log
